# Generated by Django 5.2 on 2025-05-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nehemiah_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
