# Generated by Django 5.2 on 2025-05-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nehemiah_app', '0002_alter_utilisateur_options_alter_utilisateur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='niveau_etude',
        ),
        migrations.RemoveField(
            model_name='beneficiaire',
            name='universite',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='numero_beneficiaire',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='sexe',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='reinscription',
            name='domaine_etude',
            field=models.CharField(choices=[('btp', 'Bâtiment & Travaux Publics'), ('info_eco_num', 'Informatique & Economie Numérique'), ('mgi', 'Mécanique et Génie industriel (MGI)'), ('communication', 'Communication'), ('energie', 'Energies Renouvelables et Efficacité Energétique'), ('agrobusiness', 'Agrobusiness et Industrie Agroalimentaire'), ('gestion', 'Gestion (Administration, Finances, Marketing, GRH, Comptabilité)'), ('sante', 'Sciences de la santé'), ('stylisme', 'Stylisme et modélisme')], max_length=50, verbose_name="Domaine d'étude"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
