# Generated by Django 5.2 on 2025-05-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nehemiah_app', '0003_remove_beneficiaire_niveau_etude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='numero_beneficiaire',
            field=models.CharField(default=0, max_length=9, unique=True),
        ),
    ]
