# Generated by Django 5.2 on 2025-05-28 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nehemiah_app', '0004_alter_beneficiaire_numero_beneficiaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_etude', models.CharField(choices=[('btp', 'Bâtiment & Travaux Publics'), ('info_eco_num', 'Informatique & Economie Numérique'), ('mgi', 'Mécanique et Génie industriel (MGI)'), ('communication', 'Communication'), ('energie', 'Energies Renouvelables et Efficacité Energétique'), ('agrobusiness', 'Agrobusiness et Industrie Agroalimentaire'), ('gestion', 'Gestion (Administration, Finances, Marketing, GRH, Comptabilité)'), ('sante', 'Sciences de la santé'), ('stylisme', 'Stylisme et modélisme')], max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiaire',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='message',
            name='filiere_concernee',
        ),
        migrations.RemoveField(
            model_name='reinscription',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='reinscription',
            name='valide_par',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(default='nom', max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='prenom',
            field=models.CharField(default='prenom', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nehemiah_app.groupediscussion'),
        ),
    ]
